[variables]
    NIXPACKS_PYTHON_VENV = "/opt/venv"
    NIXPACKS_PIP_INSTALL_CMD = "python3 -m pip install -r requirements.txt"

[phases.setup]
nixPkgs = ["python310", "tesseract", "libglvnd"]

[phases.install]
cmds = [
  "python3 -m ensurepip",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "PYTHONPATH=. python3 -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
